models/Pistas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "pistas".
 *
 * @property int $codigo_p
 * @property string|null $nombre
 * @property string|null $tipo
 * @property string|null $ubicacion
 * @property int|null $codigo_r
 *
 * @property Reservas $codigoR
 */
class Pistas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'pistas';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['codigo_r'], 'integer'],
            [['nombre', 'tipo', 'ubicacion'], 'string', 'max' => 20],
            [['codigo_r'], 'exist', 'skipOnError' => true, 'targetClass' => Reservas::class, 'targetAttribute' => ['codigo_r' => 'codigo_r']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'codigo_p' => 'Codigo Pista',
            'nombre' => 'Nombre',
            'tipo' => 'Tipo',
            'ubicacion' => 'Ubicacion',
            'codigo_r' => 'Codigo R',
        ];
    }

    /**
     * Gets query for [[CodigoR]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodigoR()
    {
        return $this->hasOne(Reservas::class, ['codigo_r' => 'codigo_r']);
    }
    
    public $image_url;

    // Getter method for image_url
    public function getImageUrl()
    {
        return $this->image_url;
    }

    // Setter method for image_url
    public function setImageUrl($url)
    {
        $this->image_url = $url;
    }
    
    public static function getList()
{
    $pistas = Pistas::find()->all();
    $list = [];
    foreach ($pistas as $pista) {
        $list[$pista->codigo_p] = $pista->nombre;
    }
    return $list;
}

}

controllers/PistasController.php
<?php

namespace app\controllers;

use app\models\Pistas;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PistasController implements the CRUD actions for Pistas model.
 */
class PistasController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Pistas models.
     *
     * @return string
     */
   /**
 * Lists all Pistas models.
 *
 * @return string
 */
public function actionIndex()
{
    $dataProvider = new ActiveDataProvider([
        'query' => Pistas::find(),
    ]);

    $pistas = Pistas::find()->all(); // Fetch the "Pistas" data from the database

    return $this->render('index', [
        'dataProvider' => $dataProvider,
        'pistas' => $pistas, // Pass the fetched data to the view
    ]);
}



    /**
     * Displays a single Pistas model.
     * @param int $codigo_p Codigo P
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
  public function actionView($codigo_p)
{
    $model = $this->findModel($codigo_p);

    // Assuming 'reservas' is the action name for the reservas page
    return $this->redirect(['reservas', 'codigo_p' => $model->codigo_p]);
}

    /**
     * Creates a new Pistas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Pistas();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'codigo_p' => $model->codigo_p]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pistas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $codigo_p Codigo P
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($codigo_p)
    {
        $model = $this->findModel($codigo_p);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'codigo_p' => $model->codigo_p]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pistas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $codigo_p Codigo P
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($codigo_p)
    {
        $this->findModel($codigo_p)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pistas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $codigo_p Codigo P
     * @return Pistas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($codigo_p)
    {
        if (($model = Pistas::findOne(['codigo_p' => $codigo_p])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/pistas/_court.php
<?php
use yii\helpers\Html;
?>

<div class="court-item">
    <h2><?= Html::encode($model->nombre) ?></h2>
    <div class="court-image">
        <?= Html::img($model->imageUrl, ['class' => 'img-fluid']) ?>
    </div>
    <p><?= Html::encode($model->ubicacion) ?></p>
</div>

views/pistas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Pistas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pistas-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ubicacion')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tipo')->dropDownList(['Interior' => 'Interior', 'Exterior' => 'Exterior'], ['prompt' => 'Select Tipo']) ?>

    <?= $form->field($model, 'estado')->dropDownList(['Disponible' => 'Disponible', 'Ocupada' => 'Ocupada'], ['prompt' => 'Select Estado']) ?>

    <?= $form->field($model, 'imageUrl')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'codigo_p')->dropDownList($pistasList, ['prompt' => 'Select Pista']) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/pistas/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Pistas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pistas-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ubicacion')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tipo')->dropDownList(['Interior' => 'Interior', 'Exterior' => 'Exterior'], ['prompt' => 'Select Tipo']) ?>

    <?= $form->field($model, 'estado')->dropDownList(['Disponible' => 'Disponible', 'Ocupada' => 'Ocupada'], ['prompt' => 'Select Estado']) ?>

    <?= $form->field($model, 'imageUrl')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'codigo_p')->dropDownList($pistasList, ['prompt' => 'Select Pista']) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/pistas/index.php
<?php

use yii\helpers\Html;

$this->title = 'Instalaciones';
$this->params['breadcrumbs'][] = $this->title;
?>

<h1><?= Html::encode($this->title) ?></h1>

<div class="row">
    <div class="col-md-6">
        <h2>Pistas Interior</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Tipo</th>
                    <th>Ubicación</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($dataProvider->getModels() as $pista): ?>
                    <?php if ($pista->ubicacion === 'Interior'): ?>
                        <tr>
                            <td><?= Html::encode($pista->nombre) ?></td>
                            <td><?= Html::encode($pista->tipo) ?></td>
                            <td><?= Html::encode($pista->ubicacion) ?></td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <h2>Pistas Exterior</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Tipo</th>
                    <th>Ubicación</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($dataProvider->getModels() as $pista): ?>
                    <?php if ($pista->ubicacion === 'Exterior'): ?>
                        <tr>
                            <td><?= Html::encode($pista->nombre) ?></td>
                           <td><?= Html::encode($pista->tipo) ?></td>
                            <td><?= Html::encode($pista->ubicacion) ?></td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

views/pistas/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Pistas $model */

$this->title = 'Update Pistas: ' . $model->codigo_p;
$this->params['breadcrumbs'][] = ['label' => 'Pistas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->codigo_p, 'url' => ['view', 'codigo_p' => $model->codigo_p]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="pistas-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/pistas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\Pistas $model */

$this->title = $model->codigo_p;
$this->params['breadcrumbs'][] = ['label' => 'Pistas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="pistas-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'codigo_p' => $model->codigo_p], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'codigo_p' => $model->codigo_p], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'codigo_p',
            'nombre',
            'tipo',
            'ubicacion',
            'codigo_r',
        ],
    ]) ?>

</div>