controllers/PistasController.php
<?php

namespace app\controllers;

use app\models\Pistas;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PistasController implements the CRUD actions for Pistas model.
 */
class PistasController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Pistas models.
     *
     * @return string
     */
   /**
 * Lists all Pistas models.
 *
 * @return string
 */
public function actionIndex()
{
    $dataProvider = new ActiveDataProvider([
        'query' => Pistas::find(),
    ]);

    $pistas = Pistas::find()->all(); // Fetch the "Pistas" data from the database

    return $this->render('index', [
        'dataProvider' => $dataProvider,
        'pistas' => $pistas, // Pass the fetched data to the view
    ]);
}



    /**
     * Displays a single Pistas model.
     * @param int $codigo_p Codigo P
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
  public function actionView($codigo_p)
{
    $model = $this->findModel($codigo_p);

    // Assuming 'reservas' is the action name for the reservas page
    return $this->redirect(['reservas', 'codigo_p' => $model->codigo_p]);
}

    /**
     * Creates a new Pistas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Pistas();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'codigo_p' => $model->codigo_p]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pistas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $codigo_p Codigo P
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($codigo_p)
    {
        $model = $this->findModel($codigo_p);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'codigo_p' => $model->codigo_p]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pistas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $codigo_p Codigo P
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($codigo_p)
    {
        $this->findModel($codigo_p)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pistas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $codigo_p Codigo P
     * @return Pistas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($codigo_p)
    {
        if (($model = Pistas::findOne(['codigo_p' => $codigo_p])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

controllers/TorneosController.php
<?php

namespace app\controllers;

use app\models\Torneos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * TorneosController implements the CRUD actions for Torneos model.
 */
class TorneosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'access' => [
                'class' => AccessControl::className(),
                'only' => [ 'create-torneo','update', 'delete'],
                'rules' => [
                    [
                        'actions' => ['create-torneo','update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Torneos models.
     *
     * @return string
     */
    
    public function actionCreateTorneo()
{
    $model = new Torneos();

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
        Yii::$app->session->setFlash('success', 'Torneo creado con éxito');
        return $this->redirect(['view', 'id' => $model->codigo_t]);
    }

    return $this->render('create-torneo', [
        'model' => $model,
    ]);
}

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Torneos::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'codigo_t' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Torneos model.
     * @param int $codigo_t Codigo T
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($codigo_t)
{
    $model = $this->findModel($codigo_t);
    
    $isRegistered = false;
    
    return $this->render('view', [
        'model' => $model,
        'isRegistered' => $isRegistered,
    ]);
}


    /**
     * Creates a new Torneos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Torneos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'codigo_t' => $model->codigo_t]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Torneos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $codigo_t Codigo T
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($codigo_t)
    {
        $model = $this->findModel($codigo_t);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'codigo_t' => $model->codigo_t]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Torneos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $codigo_t Codigo T
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($codigo_t)
    {
        $this->findModel($codigo_t)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Torneos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $codigo_t Codigo T
     * @return Torneos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($codigo_t)
    {
        if (($model = Torneos::findOne(['codigo_t' => $codigo_t])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public function actionRegister($codigo_t)
{
    $model = $this->findModel($codigo_t);

    return $this->redirect(['view', 'codigo_t' => $model->codigo_t]);
}



}

views/site/about.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/** @var yii\web\View $this */

$this->title = 'Club Barcenilla';
?>
<div class="site-index">
    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4">¡Bienvenido al Club de Tenis Barcenilla!</h1>
        <p class="lead">¡Has llegado al sitio web oficial de nuestro club de tenis! Aquí encontrarás información sobre nuestros servicios, eventos y cómo unirte a nuestra comunidad.</p>
    </div>

    <div class="body-content">
        <div class="row justify-content-center mb-4">
            <div class="col-lg-8 text-center">
                <h2>Servicios</h2>
                <p>En el Club de Tenis Barcenilla, ofrecemos una amplia gama de servicios para jugadores de todos los niveles. Desde canchas de tenis de última generación hasta entrenadores profesionales, estamos comprometidos en brindar la mejor experiencia de tenis.</p>
                <p>Tenemos programas de entrenamiento para principiantes, intermedios y avanzados. Además, ofrecemos servicios de alquiler de canchas, venta de equipos y organización de torneos regulares.</p>
                <p><a class="btn btn-outline-secondary" href="<?= Yii::$app->urlManager->createUrl(['reservas/index']) ?>">Más información sobre nuestros servicios &raquo;</a></p>
            </div>
        </div>

        <div class="row justify-content-center mb-4">
            <div class="col-lg-8 text-center">
                <h2>Instalaciones</h2>
                <p>Nuestro club cuenta con instalaciones de primera clase diseñadas específicamente para los amantes del tenis. Disponemos de múltiples canchas de tenis de superficie dura y arcilla, equipadas con iluminación para jugar de noche.</p>
                <p>Además, contamos con vestuarios modernos, una sala de estar cómoda y un pro shop donde puedes encontrar todo lo que necesitas para mejorar tu juego.</p>
                <p><a class="btn btn-outline-secondary" href="<?= Yii::$app->urlManager->createUrl(['pistas/index']) ?>">Explora nuestras instalaciones &raquo;</a></p>
            </div>
        </div>

        <div class="row justify-content-center mb-4">
            <div class="col-lg-8 text-center">
                <h2>Eventos</h2>
                <p>En el Club de Tenis Barcenilla, organizamos una amplia variedad de eventos para fomentar la competencia y el compañerismo entre nuestros miembros. Estos eventos incluyen torneos individuales y por parejas, ligas internas, clínicas de tenis y exhibiciones profesionales.</p>
                <p>¡No importa si eres un jugador casual o un competidor experimentado, siempre habrá una oportunidad para participar y disfrutar del tenis en un ambiente divertido y amistoso!</p>
                <p><a class="btn btn-outline-secondary" href="<?= Yii::$app->urlManager->createUrl(['torneos/index']) ?>">Descubre nuestros eventos &raquo;</a></p>
            </div>
        </div>

        <hr>

        
    </div>
</div>

views/site/login.php
<?php

use yii\bootstrap4\ActiveForm;
use yii\helpers\Html;

$this->title = 'Iniciar sesión';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Rellene lo siguiente para iniciar sesión:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        // ... other form options
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            // ... checkbox options
        ]) ?>

        <div class="form-group">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>

    <?php ActiveForm::end(); ?>
</div>